core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerenciamento.urls')),
]

gerenciamento/forms.py
from django import forms
from .models import *


class LoginForm(forms.Form):
    usuario = forms.CharField(
        label='Usuário',
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder': 'Usuário',
                'id':'usuario',
            }
        )
    )
    senha = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder': 'Senha',
                'id':'senha',
            }
        )
    )

class ProfessorForm(forms.ModelForm):
    class Meta:
        model = Professor
        fields = '__all__'
        labels = {
            'usuario': 'Usuário',
            'rg':'RG',
            'cpf':'CPF',
            'data_nascimento':'Data de Nascimento',
            'endereco':'Endereço',
            'carga_horaria_semanal':'Carga Horária Semanal',
        }
        widgets = {
            'usuario': forms.Select(attrs={'class':'form-control'}),
            'nome': forms.TextInput(attrs={'class':'form-control', 'pattern':'^[a-zA-Z0-9\s\]+$', 'placeholder':'Digite o nome do Professor'}),
            'cpf': forms.TextInput(attrs={'class':'form-control','pattern':'^[0-9]+$', 'placeholder':'Digite somente números'}),
            'rg': forms.TextInput(attrs={'class':'form-control','pattern':'^[0-9]+$', 'placeholder':'Digite somente números'}),
            'data_nascimento': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'nome@exemplo.com'}),
            'telefone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'+5513999999999'}),
            'endereco': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Rua ABC, 123'}),
            'carga_horaria_semanal': forms.SelectMultiple(attrs={'class':'form-control'}),
        }

class AlunoForm(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = '__all__'
        labels = {
            'usuario': 'Usuário',
            'rg':'RG',
            'cpf':'CPF',
            'data_nascimento':'Data de Nascimento',
            'endereco':'Endereço',
            'curso':'Curso(s)',
            'turma':'Turma',
            'data_matricula':'Data da Matrícula',
            'situacao_matricula':'Situacao da Matrícula',           
        }
        widgets = {
            'usuario': forms.Select(attrs={'class':'form-control'}),
            'nome': forms.TextInput(attrs={'class':'form-control', 'pattern':'^[a-zA-Z0-9\s\]+$', 'placeholder':'Digite o nome do Aluno'}),
            'cpf': forms.TextInput(attrs={'class':'form-control','pattern':'^[0-9]+$', 'placeholder':'Digite somente números'}),
            'rg': forms.TextInput(attrs={'class':'form-control','pattern':'^[0-9]+$', 'placeholder':'Digite somente números'}),
            'data_nascimento': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'nome@exemplo.com'}),
            'telefone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'+5513999999999'}),
            'endereco': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Rua ABC, 123'}),
            'curso': forms.SelectMultiple(attrs={'class':'form-control'}),
            'turma': forms.Select(attrs={'class':'form-control'}),
            'data_matricula': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'situacao_matricula': forms.CheckboxInput(attrs={'class':'form-check-input', 'type':'checkbox'}),
        }

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = '__all__'
        labels = {
            'nome':'Nome do Curso',
            'descricao':'Descrição do Curso',
            'duracao':'Duração do Curso',
        }
        widgets = {
            'nome': forms.TextInput(attrs={'class':'form-control', 'pattern':'^[a-zA-Z0-9\s\]+$', 'placeholder':'Digite o nome do Curso'}),
            'descricao': forms.Textarea(attrs={'class':'form-control', 'pattern':'^[a-zA-Z0-9\s\]+$', 'placeholder':'Digite a descrição do Curso'}),
            'duracao': forms.TextInput(attrs={'class':'form-control','pattern':'^[a-zA-Z0-9\s\]+$', 'placeholder':'000 horas'}),
        }

class TurmaForm(forms.ModelForm):
    class Meta:
        model = Turma
        fields = '__all__'
        labels = {
            'nome':'Nome da Turma',
            'professor':'Professor(es)',
            'carga_horaria_semanal':'Carga Horária Semanal'
        }
        widgets = {
            'nome': forms.TextInput(attrs={'class':'form-control', 'pattern':'^[a-zA-Z0-9\s\]+$', 'placeholder':'Digite o nome da Turma'}),
            'professor': forms.SelectMultiple(attrs={'class':'form-control'}),
            'carga_horaria_semanal': forms.SelectMultiple(attrs={'class':'form-control'}),
        }

class AulaForm(forms.ModelForm):
    class Meta:
        model = Aula
        fields = '__all__'
        labels = {

        }
        widgets = {
            'curso': forms.Select(attrs={'class':'form-control'}),
            'dia_da_semana': forms.Select(attrs={'class':'form-control'}),
            'hora_do_dia': forms.Select(attrs={'class':'form-control'}),
            'professor': forms.Select(attrs={'class':'form-control'}),
            'turma': forms.Select(attrs={'class':'form-control'}),
            
        }

class MensagemForm(forms.ModelForm):
    class Meta:
        model = Mensagem
        fields = ["destinatario", "assunto", "conteudo"]
        labels = {
            "destinatario": "Destinatário",
            "assunto": "Assunto",
            "conteudo": "Mensagem",
        }
        widgets = {
            "destinatario": forms.Select(attrs={'class':'form-control'}),
            "assunto": forms.TextInput(attrs={'class':'form-control'}),
            "conteudo": forms.Textarea(attrs={'class':'form-control'}),
        }

class RespostaForm(forms.ModelForm):
    class Meta:
        model = Mensagem
        fields = ["conteudo"]
        labels = {
            "conteudo":"Resposta",
        }
        widgets = {
            "conteudo": forms.Textarea(attrs={'class':'form-control border border-2'}),
        }

templates/login/deslogar.html
{% extends "base.html" %}
{% block base %}
<div class='col-6 mx-auto border border-3 p-5 rounded-5'>
    <h3 class='text-center'>Sessão encerrada com sucesso.</h3><br>
    <p><a class="btn btn-secondary" href="{% url "qel" %}">Voltar a página de login!</a></p>
</div>
{% endblock base %}

templates/login/login_da_escola.html
{% extends "base.html" %}
{% block base %}
<div class='col-6 mx-auto border border-4 p-5 rounded-5'>
    <div class='text-center'>
        <h2>Login do Administrador</h2>
    </div>
    <br>
    <div>
        {% if messages %}
            <div class='container mt-3'>
                {% for message in messages %}
                    <div class='alert alert-danger alert-dismissible fade show' role='alert'>
                        {{ message }}
                        <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='close'></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div>
        <form action="{% url "log_esc" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div>
                <input class='btn btn-success' type="submit" value="Entrar">
                <a href="{% url "qel" %}" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>        
</div>
{% endblock base %}

templates/login/login_do_aluno.html
{% extends "base.html" %}
{% block base %}
<div class='col-6 mx-auto border border-4 p-5 rounded-5'>
    <div class='text-center'>
        <h2>Login do Aluno</h2>
    </div>
    <br>
    <div>
        {% if messages %}
        <div>
            {% for message in messages %}
            <div class='alert alert-danger alert-dismissible fade show' role='alert'>
                {{ message }}
                <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='close'></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <div>
        <form action="{% url "log_alu" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div>
                <input class='btn btn-success' type="submit" value="Entrar">
                <a href="{% url "qel" %}" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock base %}

templates/login/login_do_professor.html
{% extends "base.html" %}
{% block base %}
<div class='col-6 mx-auto border border-4 p-5 rounded-5'>
    <div class='text-center'>
        <h2>Login do Professor</h2>
    </div>
    <br>
    <div>
        {% if messages %}
        <div>
            {% for message in messages %}
            <div class='alert alert-danger alert-dismissible fade show' role='alert'>
                {{ message }}
                <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='close'></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>

    <div>
        <form action="{% url "log_pro" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div>
                <input class='btn btn-success' type="submit" value="Entrar">
                <a href="{% url "qel" %}" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock base %}

templates/login/registrar_novo_login.html
{% extends "gerenciamento/base.html" %}
{% block corpo %}
<div class='col-10 mx-auto'>
    <div class='text-center'>
        <h2><strong>Registrar um novo usuário</strong></h2>
    </div>
    <div class='col-7 mx-auto border border-3 rounded-5 p-5'>
        <form action="{% url "add_log" %}" method="post">
            {% csrf_token %}
            <p><label for="id_usuario">Usuário:</label>
                <input class='form-control' type="text" name="usuario" id='id_usuario' autocomplete='off' required></p>
            <p><label for="id_senha">Senha:</label>
                <input class='form-control' type="password" name="senha" autocomplete='new-password' id='id_senha' minlength='8' required></p>
            <p><label for="id_primeiro_nome">Primeiro Nome:</label>
                <input class='form-control' type="text" name="primeiro_nome" id='id_primeiro_nome' autocomplete='off' required></p>
            <p><label for="id_ultimo_nome">Ultimo Nome:</label>
                <input class='form-control' type="text" name="ultimo_nome" id='id_ultimo_nome' autocomplete='off' required></p>
            <p><label for="id_grupo_login">Tipo de Login:</label>
                <select class='form-control' name="grupo_login" id="id_grupo_login" required>
                    <option value="2">Escola</option>
                    <option value="3">Professor</option>
                    <option value="4">Aluno</option>
                </select></p>
            <br>
            <div>
                <input class='btn btn-success' type="submit" value="Registrar">
                <a class='btn btn-danger' href="{% url "indexescola" %}">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock corpo %}

templates/login/tipo_de_login.html
{% extends "base.html" %}
{% block base %}
<div class='col-6 mx-auto text-center'>
    <h1>Quem está logando?</h1><br>
    <div>
        <h4><a class='list-group-item p-5 border border-3 rounded-5' href="{% url "log_esc" %}">Escola</a></h>
    </div>
    <br>
    <div>
        <h4><a class='list-group-item p-5 border border-3 rounded-5' href="{% url "log_pro" %}">Professor</a></h4>
    </div>
    <br>
    <div>
        <h4><a class='list-group-item p-5 border border-3 rounded-5' href="{% url "log_alu" %}">Aluno</a></h4>
    </div>
    <br>
</div>
{% endblock base %}